version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.htpasswd:/etc/nginx/.htpasswd
      - ./static:/usr/share/nginx/html
      - ./log:/var/log/nginx/
    restart: unless-stopped
